name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: "9.15.0"
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Run tests before building
        run: |
          pnpm test
          pnpm test:coverage

      - name: Install Playwright browsers for testing
        run: pnpm exec playwright install --with-deps chromium

      - name: Run E2E tests for Chrome
        run: pnpm test:e2e:chrome

      - name: Build and package Chrome extension
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: pnpm package

      - name: Build and package Firefox extension
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: pnpm package:firefox

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: CC Generator v${{ steps.get_version.outputs.VERSION }}
          files: |
            build/cc-generator-v${{ steps.get_version.outputs.VERSION }}.zip
            build/cc-generator-firefox-v${{ steps.get_version.outputs.VERSION }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
